### ISSUE TITLE
code for eclips

### ISSUE THREAD

**Issue by erpragatisingh** [makovkastar/FloatingActionButton#106]
how can we import project into eclipse. 
Thanks

**Comment by Papetz** [comment]
1) Import it as a project into Eclipse, File -> Import.. (check copy into workspace, and rename it as Fab library) 

2) Right-click in the project's name, go to Properties and under "Android" check "Is library".

3) Right click Your project -> Android -> Add... and check the Fab library

**Comment by makovkastar** [comment]
Please switch to the Android Studio and you will not have any problems with importing this library. Thanks.

**Comment by erpragatisingh** [comment]
from initial most user available for eclipse.Thanks.
