### ISSUE TITLE
FloatingActionButton is messing up with the RecyclerView listener.

### ISSUE THREAD

**Issue by astinx** [makovkastar/FloatingActionButton#109]
Hi, I have a RecyclerView inside a SwipeRefreshLayout. I use the RecyclerView.OnScrollListener callback to perform the pagination request. The thing is that when I set the FloatingActionButton, using the attachRecyclerView method, this method must override the OnScrollListener callback and thus disable my pagination requests. Is there anyway that I could set the FloatingActionButton without override my RecyclerView OnScrollListener callback?. Thanks, pretty usefull library, saved me a lot of work!.

**Comment by dirkam** [comment]
This seems to be the same as #99. Check that issue for a workaround that might be useful for you.

**Comment by astinx** [comment]
Thanks!, I tried to find an issue similar, but I didn't find it. Sorry that I bring back something old :/.

**Comment by bdonahue** [comment]
I fixed this over here: https://github.com/makovkastar/FloatingActionButton/pull/101
Still waiting for it to get merged.
