### ISSUE TITLE
Integrate FAB

### ISSUE THREAD

**Issue by rcastill** [makovkastar/FloatingActionButton#114]
Is there a way to integrate this lib without gradle? (I'm using IntelliJ IDEA as IDE)

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
Same issue here, considering utilizing another library instead.

**Comment by makovkastar** [comment]
@rcastill did you succeed with importing the library using answer from @RaymondBakkerMoonlightMultimedia?

**Comment by makovkastar** [comment]
No answer. Closing...
