### ISSUE TITLE
FAB doesn't work with Maven.

### ISSUE THREAD

**Issue by pkhivesara** [makovkastar/FloatingActionButton#115]
Trying to use the library as a dependency via Maven Central. The dependency link:
http://search.maven.org/#artifactdetails%7Ccom.melnykov%7Cfloatingactionbutton%7C1.1.0%7Caar

```xml
<pre><code><dependency>
    <groupId>com.melnykov</groupId>
    <artifactId>floatingactionbutton</artifactId>
    <version>1.1.0</version>
</dependency></code></pre>

```
Looking at the /.m2 folder all i see is _maven.repo, floatingactionbutton.pom and floatingactionbutton.pom.sha1 files. Cannot find the jar. 

I am missing something here?

**Comment by makovkastar** [comment]
The FAB library is packaged as an AAR archive so there is not JAR file. Please try the following dependency and let me know if it works:

```xml
<dependency>
    <groupId>com.melnykov</groupId>
    <artifactId>floatingactionbutton</artifactId>
    <version>1.2.0</version>
    <type>aar</type>
</dependency>
```

**Comment by pkhivesara** [comment]
So why does the FAB search on maven central yield this: 

```xml
<dependency>
    <groupId>com.melnykov</groupId>
    <artifactId>floatingactionbutton</artifactId>
    <version>1.2.0</version>
</dependency>

```

The ```<type> ``` seems to be missing from the dependency. Does this need to be updated or did i miss something from maven central? I shall try using the aar and put an updated comment soon.

Thanks!

**Comment by pkhivesara** [comment]
Ok using the aar tag did work fine! Thanks!
