### ISSUE TITLE
Changing the FAB color

### ISSUE THREAD

**Issue by mithunm93** [makovkastar/FloatingActionButton#118]
I'm simply trying to change the color of the FAB, the normal, pressed, and ripple. But I'm unable to do so successfully. If I changed the colors in the XML file like this:

``` XML
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/tools"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ImageView
            android:id="@+id/drinkImage"
            android:layout_width="match_parent"
            android:layout_height="300dp"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop"
            android:gravity="left"
            android:transitionName="@string/drink_image_transition"
            />

        <TextView
            android:padding="8dp"
            android:id="@+id/drinkName"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="24sp"
            android:textColor="@color/text_primary"
            android:transitionName="@string/drink_name_transition"
            />

        <com.melnykov.fab.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/drinkImage"
            android:layout_margin="16dp"
            android:src="@drawable/fab_ic_add"
            fab:fab_colorNormal="@color/accent"
            fab:fab_colorPressed="@color/primary_pressed"
            fab:fab_colorRipple="@color/ripple"/>

    </RelativeLayout>
</ScrollView>
```

This does absolutely nothing, the color remains the default one included in the library. Those attributes are ones I set in my colors.xml file. For example: @color/accent is #E91E63.

If I change the color from the code (the onCreate() method in the new Activity) itself like this:

```Java
        //set up FAB
        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setColorNormal(R.color.accent);
        fab.setColorPressed(R.color.primary);
        fab.setColorRipple(R.color.primary_dark);
```

But the FAB shows up like in this screenshot. The button is not being pressed, it's "normal" state looks like that.

![screenshot_2015-02-03-21-10-35](https://cloud.githubusercontent.com/assets/7864039/6034625/91e92e48-abea-11e4-826b-bcd4daaf7d21.png)

Maybe I'm doing something incorrectly, what am I supposed to do?

**Comment by mithunm93** [comment]
I figured it out, for some reason, my XML had this line:

```XML
xmlns:fab="http://schemas.android.com/tools"
```
 as you can see above, instead of this line:

```XML
xmlns:fab="http://schemas.android.com/apk/res-auto"
```
not sure how that came to be, I used the auto-import. I only figured it out when I added the FAB to another Activity, and it showed up correctly (strangely enough I used the auto-import for this activity too, but it retrieved the different URL shown above).

**Comment by jd-alexander** [comment]
Same thing just happened with me. Good thing I stumbled upon this.

**Comment by nishantmendiratta** [comment]
Any updates on this ?

**Comment by sujanakal** [comment]
Even I had the same issue. Thank you so much..
