### ISSUE TITLE
Issues with API level 19.

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [makovkastar/FloatingActionButton#122]
Repeition steps.

Open Android studio layout using FAB at API level 21.
Turn the layout landscape.
Switch to API level 19.

Receive 
![screen shot 2015-02-11 at 21 25 16](https://cloud.githubusercontent.com/assets/3738421/6156777/7c055868-b234-11e4-8dd0-efe660f5ac78.png)

**Comment by makovkastar** [comment]
Hi, thanks for reporting the issue. But it seems it's a bug in the Android Studio UI Preview. With API 21 selected for the preview the FAB is rendered correctly.

Here is a ling to issue thread: https://code.google.com/p/android/issues/detail?id=75204.
