### ISSUE TITLE
does allow to add another scroll listener

### ISSUE THREAD

**Issue by jjhesk** [makovkastar/FloatingActionButton#123]
I have found that once that scroll tracker is attached to the listview and the list view it self would able to track the scroll by onScroll method. The code is shown as below:

```java

         mGrid = (JazzyGridView) v.findViewById(android.R.id.list); // First I declare the list view in here
        madapter = new HBResultAdapter(getActivity(), R.layout.l_griditem);
        mGrid.setAdapter(madapter);
        mGrid.setTransitionEffect(JazzyHelper.FADE);
        mGrid.setShouldOnlyAnimateNewItems(false);
         mGrid.setOnScrollListener(this); // add to the first list view
 
  

         FloatingActionButton fab = (FloatingActionButton) v.findViewById(R.id.fab); //find the button
         fab.attachToListView(mGrid); // and add the list view with the button scroll tracker
        



```
please let me know if i can fix this..

JazzyGridView is extended from the GridView

**Comment by bdonahue** [comment]
This should fix it:

Delete this line: mGrid.setOnScrollListener(this); // add to the first list view

Change this line 
from: fab.attachToListView(mGrid);
to: fab.attachToListView(mGrid, null, this);

**Comment by jjhesk** [comment]
I have confirmed that this is working now! Thank you, you are great @bdonahue
