### ISSUE TITLE
Black box around button

### ISSUE THREAD

**Issue by asco33** [makovkastar/FloatingActionButton#131]
On some smaller devices, for example the Acer Liquid Z4 (Android version 4.2.2, screen 480x800) or the Genymotion Galaxy S2 image (Android version 4.1.1, screen 480x800) the FABs in my project 
have a black box around them: 
![duug3](https://cloud.githubusercontent.com/assets/4496883/6475461/ca01c14c-c20a-11e4-8826-4ff1d461e813.png)

I tried to narrow this down, removed any special stuff from my theme making it look like this:

```sh
<!-- Base application theme. -->
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    <!-- Customize your theme here. -->
</style>
```

and also put onbe button without any attributes in the most simple layout:

```sh
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:paddingLeft="@dimen/activity_horizontal_margin"
                android:paddingRight="@dimen/activity_horizontal_margin"
                android:paddingTop="@dimen/activity_vertical_margin"
                android:paddingBottom="@dimen/activity_vertical_margin"
                tools:context="de.immowelt.android.immobiliensuche.ui.FabTestActivity">


    <com.melnykov.fab.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>

</RelativeLayout>
```

but the box remains. 

A way to make it disappear is to remove the shadow with

```sh
  fab:fab_shadow="false"
```

Also the 'bug' is only present with the normal size FAB and is gone when using the mini size. 

I tried to recreate the effect with a new project but couldn't do it.

I'm using version 1.2.0.

Any ideas on what my problem is?

**Comment by asco33** [comment]
The problem was that the `FloatingActionButton` class makes use of a drawable called `shadow.9.png` for the shadow. I also had a `shadow.9.png` in my drawables and the library class obviously picked up the wrong one (mine).

**Comment by makovkastar** [comment]
Hi, I'm glad that the problem is resolved though it was a bit tricky.
