### ISSUE TITLE
NumberFormatException:Invalid int: ".0dip" on Android 4.1

### ISSUE THREAD

**Issue by guo314159** [makovkastar/FloatingActionButton#136]
Hi , I met a bug on Android 4.1

may be other people also met this bug.

I doesn't have the devices, so I can't reappear this bug.

but it have appear 56 times on our logs that uploaded to our servers

cause by:
java.lang.reflect.InvocationTargetException
java.lang.reflect.Constructor.constructNative(Native Method)
java.lang.reflect.Constructor.newInstance(Constructor.java:417)
android.view.LayoutInflater.createView(LayoutInflater.java:587)
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
android.view.LayoutInflater.inflate(LayoutInflater.java:489)
android.view.LayoutInflater.inflate(LayoutInflater.java:396)
cn.jaxus.course.control.my.discuss.DiscussFragment.android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)(Unknown Source)
android.support.v4.app.Fragment.android.view.View performCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)(Unknown Source)
android.support.v4.app.FragmentManagerImpl.void moveToState(android.support.v4.app.Fragment,int,int,int,boolean)(Unknown Source)
                                           void moveToState(android.support.v4.app.Fragment)
                                           void moveToState(int,boolean)
                                           void moveToState(int,int,int,boolean)
android.support.v4.app.FragmentManagerImpl.void moveToState(android.support.v4.app.Fragment,int,int,int,boolean)(Unknown Source)
                                           void moveToState(android.support.v4.app.Fragment)
                                           void moveToState(int,boolean)
                                           void moveToState(int,int,int,boolean)
android.support.v4.app.BackStackRecord.void run()(Unknown Source)
android.support.v4.app.FragmentManagerImpl.boolean execPendingActions()(Unknown Source)
android.support.v4.app.FragmentManagerImpl.boolean executePendingTransactions()(Unknown Source)
android.support.v4.app.FragmentPagerAdapter.void finishUpdate(android.view.ViewGroup)(Unknown Source)
android.support.v4.view.ViewPager.void populate()(Unknown Source)
                                  void populate(int)
android.support.v4.view.ViewPager.void populate()(Unknown Source)
                                  void populate(int)
android.support.v4.view.ViewPager.void onMeasure(int,int)(Unknown Source)
android.view.View.measure(View.java:15282)
android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
android.view.View.measure(View.java:15282)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
android.view.View.measure(View.java:15282)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
android.support.v7.internal.widget.ActionBarOverlayLayout.void onMeasure(int,int)(Unknown Source)
android.view.View.measure(View.java:15282)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
android.view.View.measure(View.java:15282)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
android.view.View.measure(View.java:15282)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2167)
android.view.View.measure(View.java:15282)
android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2140)
android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1251)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1444)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1136)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4631)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
android.view.Choreographer.doCallbacks(Choreographer.java:567)
android.view.Choreographer.doFrame(Choreographer.java:536)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:733)
android.os.Handler.handleCallback(Handler.java:615)
android.os.Handler.dispatchMessage(Handler.java:92)
android.os.Looper.loop(Looper.java:153)
android.app.ActivityThread.main(ActivityThread.java:5108)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
dalvik.system.NativeStart.main(Native Method)
cause by:
java.lang.NumberFormatException:Invalid int: ".0dip"
java.lang.Integer.invalidInt(Integer.java:138)
java.lang.Integer.parse(Integer.java:375)
java.lang.Integer.parseInt(Integer.java:366)
com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:123)
android.content.res.TypedArray.getInt(TypedArray.java:254)
android.view.View.<init>(View.java:3627)
android.widget.ImageView.<init>(ImageView.java:114)
android.widget.ImageButton.<init>(ImageButton.java:87)
android.widget.ImageButton.<init>(ImageButton.java:83)
cn.jaxus.course.common.widget.button.floataction.FloatingActionButton.<init>(Unknown Source)
java.lang.reflect.Constructor.constructNative(Native Method)
java.lang.reflect.Constructor.newInstance(Constructor.java:417)
android.view.LayoutInflater.createView(LayoutInflater.java:587)
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
android.view.LayoutInflater.inflate(LayoutInflater.java:489)
android.view.LayoutInflater.inflate(LayoutInflater.java:396)

**Comment by guo314159** [comment]
it only appears on Android 4.1

**Comment by guo314159** [comment]
No, I found it also appears on 5.0.1, it not depends on android version

**Comment by guo314159** [comment]
it is a System bug. 
http://stackoverflow.com/questions/25964129/inflator-throws-numberformatexception-invalid-int-20-0dip-on-samsung-galaxy-ta

**Comment by makovkastar** [comment]
If it's a device specific bug, I'm going to close this issue. Thanks for investigation.
