### ISSUE TITLE
Please rename shadow drawables with a prefix

### ISSUE THREAD

**Issue by corwin42** [makovkastar/FloatingActionButton#140]
I added your library to a project and the result was that the normal sized FAB had a wrong shadow on pre lollipop devices. After searching around I found out that I had a shadow.png in the projects res/drawable-xxx folders. So the shadow drawable of the FAB got overwritten by this local resource.

Google recommends to name resources with a prefix to avoid such conflicts. Can you please rename the drawables to fab_shadow.png and fab_shadow_mini.png? I think this would avoid such conflicts most times.

**Comment by makovkastar** [comment]
Hi, thanks for reporting an issue. Could you send me a PR?

**Comment by makovkastar** [comment]
Fixed by 95d549fd733d44e55763011c73beeb2fca854a96.
