### ISSUE TITLE
ScrollView cannot be cast to com.melnykov.fab.ObservableScrollView

### ISSUE THREAD

**Issue by samiro** [makovkastar/FloatingActionButton#141]
compileSdkVersion 21
minSdkVersion 15
targetSdkVersion 21

What happen?

**Comment by IlyaEremin** [comment]
ObservableScrollView extends ScrollView. You can cast from ObservableScrollView to ScrollView, but not vise versa. See casting objects at http://docs.oracle.com/javase/tutorial/java/IandI/subclasses.html

**Comment by makovkastar** [comment]
@IlyaEremin is right. Closing this issue.
