### ISSUE TITLE
shadow.png doesn't have ideal oval form for some resolutions.

### ISSUE THREAD

**Issue by kshilovskiy** [makovkastar/FloatingActionButton#144]
The bottom border of the shadow.png(mdpi,hdpi, xhdpi) doesn't have an oval form. As it can be seen on the attached image it is cut. It becomes visible on white areas.
http://cl.ly/image/1k0s1J2s2f0i

**Comment by Rolf-Smit** [comment]
This should be fixed as soon as possible, it's quit annoying!

**Comment by makovkastar** [comment]
Now it looks good for me. What do you guys think?
![image-2015-03-24-at-8 22](https://cloud.githubusercontent.com/assets/1076309/6993145/cd84ed60-daf3-11e4-8426-8f9ea89e65c9.png)

**Comment by makovkastar** [comment]
Fixed with 95d549fd733d44e55763011c73beeb2fca854a96.

**Comment by Rolf-Smit** [comment]
Looks good! Will this be in version 1.3?

Btw: I'm using the library in the app Tinycore (30.000 downloads, https://play.google.com/store/apps/details?id=org.neotech.app.tinycore)

**Comment by makovkastar** [comment]
Yes, I'm going to release the version 1.3 with this fix soon.
