### ISSUE TITLE
Can't use in Eclipse

### ISSUE THREAD

**Issue by konopkoman** [makovkastar/FloatingActionButton#148]
Eclispe doesn't find a classes

**Comment by jaredsburrows** [comment]
It's time to upgrade to Intellij or Android Studio anyways for Android Development or at least use Maven or Gradle for the dependencies.

**Comment by YoungjaeKim** [comment]
I think it's good to close the issue. Eclipse is officially out of support by google also.

**Comment by GGGGeek** [comment]
obviously,eclipse is outdated(#ﾟДﾟ)

在 2015-07-20 13:34:41，YoungjaeKim <notifications@github.com> 写道：


I think it's good to close the issue. Eclipse is officially out of support by google also.
