### ISSUE TITLE
onClick listener

### ISSUE THREAD

**Issue by WonderlustKing** [makovkastar/FloatingActionButton#159]
Hello, how can i set onClick listener on the fab? I try 
fab.setOnClickListener(new View.OnClickListener() { ......});
but nothing happened.

**Comment by makovkastar** [comment]
The FAB extends the standard ``ImageButton`` class and doesn't override ``setOnClickListener``. So please double-check, what you do should work.

**Comment by dekaru** [comment]
I had the same issue when trying to add a white overlay when the Fab Menu is opened:

        // add OnClickListener to change the background color
        fabAttachments.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (fabAttachments.isOpened())
                    fabAttachments.setBackgroundColor(0x00000000);
                else
                    fabAttachments.setBackgroundColor(getResources().getColor(R.color.white_transparent));
            }
        });

The OnClickListener is registered on the OnCreate but it doesn't get called. Any ideas?
