### ISSUE TITLE
Views below FABMenuButton are not clickable

### ISSUE THREAD

**Issue by vitovalov** [makovkastar/FloatingActionButton#174]
Hi,
just wanted to report an issue I've found when set an onClickListener to the fab menu button itself.
I hadn't seen your examples at first so that was my first thought. 
It seems that doing so will prevent other views below the whole menu button (even if it's collapsed) to handle onClick events. The whole area that would occupy the expanded menu button is not clickable.

I suggest to hide the `setOnClickListener` from the public methods or ducument it at least.

**Comment by makovkastar** [comment]
Hi, it seems you posted the issue to the wrong repo. There is no FABMenuButton in this library.
