### ISSUE TITLE
FAB lacks "lift on press"

### ISSUE THREAD

**Issue by nwalters512** [makovkastar/FloatingActionButton#181]
Per the material spec, FABs should "lift" towards the surface of the screen when pressed. However, this library doesn't include such behavior. This would probably apply only to 5.x+ devices since they have the elevation API; since the shadow is drawn with a bitmap on pre-Lollipop devices, animating the elevated shadow would be difficult.

**Comment by MrBrightside29** [comment]
+1

**Comment by nwalters512** [comment]
This library is now deprecated.
