### ISSUE TITLE
FAB isn't appearing on some devices.

### ISSUE THREAD

**Issue by TheAndroidMaster** [makovkastar/FloatingActionButton#191]
My app is having some problems: I have a listview with about 60-100 items in it, and on some devices the fab isn't showing up. So far I have only confirmed that it works on my HTC Desire 816 (5.0). It isn't working on a Dell Venue tablet (4.2) and a Moto X (unknown android version).

Here is my java:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_felix_launcher_home);

        ListView listView = (ListView) findViewById(android.R.id.list);
        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);

        fab.setShadow(true);
        fab.attachToListView(listView);

        TextClock textClock = (TextClock) findViewById(R.id.textClock);

        textClock.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent openClockIntent = new Intent(AlarmClock.ACTION_SET_ALARM);
                openClockIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                FelixLauncherHome.this.startActivity(openClockIntent);
            }
        });

        loadApps();
        loadListView();
        addClickListener();
        ClickListenerfordafab();
    }

    private void ClickListenerfordafab() {
        findViewById(R.id.fab).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent lays = manager.getLaunchIntentForPackage("com.google.android.googlequicksearchbox");
                FelixLauncherHome.this.startActivity(lays);
            }
        });

    }

    private PackageManager manager;
    private List<AppDetail> apps;

    private void loadApps() {
        manager = getPackageManager();
        apps = new ArrayList<AppDetail>();

        Intent i = new Intent(Intent.ACTION_MAIN, null);
        i.addCategory(Intent.CATEGORY_LAUNCHER);

        List<ResolveInfo> availableActivities = manager.queryIntentActivities(i, 0);
        for (ResolveInfo ri : availableActivities) {
            AppDetail app = new AppDetail();
            app.label = ri.loadLabel(manager);
            app.name = ri.activityInfo.packageName;
            app.icon = ri.activityInfo.loadIcon(manager);
            apps.add(app);
        }
    }

    private ListView list;

    private void loadListView() {
        list = (ListView) findViewById(android.R.id.list);

        ArrayAdapter<AppDetail> adapter = new ArrayAdapter<AppDetail>(this,
                R.layout.list_item,
                apps) {
            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                if (convertView == null) {
                    convertView = getLayoutInflater().inflate(R.layout.list_item, null);
                }

                ImageView appIcon = (ImageView) convertView.findViewById(R.id.item_app_icon);
                appIcon.setImageDrawable(apps.get(position).icon);

                TextView appLabel = (TextView) convertView.findViewById(R.id.item_app_label);
                appLabel.setText(apps.get(position).label);

                TextView appName = (TextView) convertView.findViewById(R.id.item_app_name);
                appName.setText(apps.get(position).name);

                return convertView;
            }
        };

        list.setAdapter(adapter);
    }

    private void addClickListener() {
        list.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> av, View v, int pos,
                                    long id) {
                Intent i = manager.getLaunchIntentForPackage(apps.get(pos).name.toString());
                FelixLauncherHome.this.startActivity(i);
            }
        });
    }

And here is the xml file:

    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical"
    android:background="#e0e0e0">

    <TextClock
        tools:ignore="NewApi"
        android:layout_width="fill_parent"
        android:layout_height="50dp"
        android:id="@+id/textClock"
        android:background="#212121"
        android:textColor="#ffffff"
        android:layout_gravity="top|center"
        android:gravity="center_vertical|center_horizontal"
        android:textSize="30dp" />

    <com.melnykov.fab.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="16dp"
        android:src="@mipmap/search"
        fab:fab_colorNormal="#ffffff"
        fab:fab_colorPressed="#dfdfdf"
        fab:fab_colorRipple="#000000"
        fab:fab_shadow="true"
        fab:fab_type="normal"
        android:layout_gravity="bottom|end"
        android:visibility="visible"
        android:paddingTop="10dp" />

    <ListView
        android:id="@android:id/list"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:background="#000000"
        android:layout_gravity="bottom"
        android:layout_marginTop="50dp">
    </ListView>

    </FrameLayout>

**Comment by nwalters512** [comment]
Have you tried this with a regualr drawable instead of a mipmap? AFAIK mipmap support was only added in 4.3.

**Comment by TheAndroidMaster** [comment]
Sorry, I fixed this issue a while ago and forgot to close it here. Moving the fab to the bottom of the layout file fixed the issue. I am kind of curious why, but it works, so the issue is closed.
