### ISSUE TITLE
floatingactionbutton cannot show.when i scroll down slowly? 

### ISSUE THREAD

**Issue by SsKarthi** [makovkastar/FloatingActionButton#212]
floating action button not showing when i scroll down slowly.i m using recyclerview like
**
        fab.attachToRecyclerView(recyclerView);
**

**Comment by wjnovember** [comment]
![image](https://cloud.githubusercontent.com/assets/12218174/20167186/c14247c6-a754-11e6-8125-44a6a8973dc5.png)

Your can try changing the value of **mScrollThreshold**, the default value is belowing:
![image](https://cloud.githubusercontent.com/assets/12218174/20167220/ffd7e324-a754-11e6-850d-ed6e8896c686.png)
