### ISSUE TITLE
two FAB's attached to same listview

### ISSUE THREAD

**Issue by nmrainho** [makovkastar/FloatingActionButton#48]
If i attach two fabs to the same list view only one listens the onScroll so only one hides when scrolling.
Is there a way to attach both of them to onScroll?
Thanks

**Comment by vyscond** [comment]
Sorry for the necrobump but i cant find the __FabOnScrollListener__ as you described.

**Comment by GillesC** [comment]
@vyscond In the new version you have to use new ScrollDirectionListener() instead of FabOnScrollListener()

**Comment by vyscond** [comment]
Better late than never! Thanks @GillesC
