### ISSUE TITLE
weird boundary around the button

### ISSUE THREAD

**Issue by bearprada** [makovkastar/FloatingActionButton#84]
![device-2014-12-11-120555](https://cloud.githubusercontent.com/assets/1080103/5388875/347b2c2a-812e-11e4-9478-3bdd0740ef47.png)

i try to integrate this library to my project. but it looks weird when running on non-Lollipop devices

is it any idea for this ?

**Comment by makovkastar** [comment]
Hi! Did you fix this issue?

**Comment by bearprada** [comment]
no ~ but i use another library https://github.com/futuresimple/android-floating-action-button (it's reference on your implementation. but it's work)

**Comment by makovkastar** [comment]
But in your posted xml layout you didn't use my library but already this one: https://github.com/futuresimple/android-floating-action-button. Did you post wrong layout?

**Comment by shakmak** [comment]
Facing exactly same issues. I am using icon from your sample so it doesn't have any boundary. 
I copied your activity and layout file to my project and still facing same issues though your sample runs file.
