### ISSUE TITLE
Shadow problem

### ISSUE THREAD

**Issue by pcevikogullari** [makovkastar/FloatingActionButton#85]
![screenshot_2014-12-12-02-17-32](https://cloud.githubusercontent.com/assets/3846607/5404904/ac9945ee-81a5-11e4-9e55-525b904a8c8f.png)
![screenshot_2014-12-12-02-17-42](https://cloud.githubusercontent.com/assets/3846607/5404905/accd54b0-81a5-11e4-8cc6-3b688e790d0f.png)

Is there a way to set elevation level? I implemented your button but don't think it is worked. I attached the screenshots ( one of them my project, the other one is yours). Do you think it is working? Or it is just a low shadow because your shadow is deeper? Thanks!

**Comment by makovkastar** [comment]
Hi! You can set elevation level only on API >= 21. For pre-Lollipop shadow is used as a graphical asset so cannot be changed.

**Comment by mufumbo** [comment]
@makovkastar the graphical asset cannot be fixed?

**Comment by makovkastar** [comment]
@mufumbo What do you mean? Shadow on pre-Lollipop is implemented using shipped with the library shadow image of the exact size. How can it be fixed?
