### ISSUE TITLE
Is it possible to know when the FAB view is starting/finishing its animations?

### ISSUE THREAD

**Issue by valbertos** [makovkastar/FloatingActionButton#92]
If it isn’t, I think an interface like this would do the trick:

    public interface FABAnimationListener() {
	    public void onStartShowAnimation() {}

	    public void onEndShowAnimation() {}

	    public void onStartHideAnimation() {}

	    public void onEndHideAnimation() {}
    }

I need this feature to synchronise the moment when the ActionBar is hidden. 

Thanks!

**Comment by makovkastar** [comment]
You may use ``attachXXX`` methods with the second argument of type ``ScrollDirectionListener``. ``ScrollDirectionListener`` has ``onScrollDown`` and ``onScrollUp`` callbacks to track the state of the FAB. Or do you need to know when the animation exactly starts and stops?
