### ISSUE TITLE
How to set "android:src" programmatically for fab?

### ISSUE THREAD

**Issue by IRMobydick** [makovkastar/FloatingActionButton#93]
I need to change Image source of fab by situation in my app. How can do that?
Unfortunately common ways does not work!

**Comment by forcewill** [comment]
calling setImageBitmap doesn't appear to scale the image properly (FAB goes from being a circle to the ratio of the bitmap square/rectangle), 
on Samsung Galaxy S5

Tried with 
android:scaleType="centerCrop" also and the effect was the same

**Comment by davidwu0709** [comment]
@forcewill , firstly, you need to setPadding(-1, -1, -1, -1, then crop circular area from bitmap and set it to FAB with setImageBitmap function.
