### ISSUE TITLE
shadow on colored background

### ISSUE THREAD

**Issue by dirkam** [makovkastar/FloatingActionButton#95]
The shadow is weird if it's on top of a colored background. Example:
![image](https://cloud.githubusercontent.com/assets/6302839/5589224/4fd6c78a-911a-11e4-990b-8552a1480cea.png)

Can you please check it?

**Comment by makovkastar** [comment]
Hi! I checked it by using a background color for list in the sample. Shadow looks good:
![device-2015-01-05-171053](https://cloud.githubusercontent.com/assets/1076309/5614074/b9ae9d0c-94f5-11e4-8bcb-f3db25cc863c.png)
